# Generated by Django 5.0.1 on 2024-01-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['department_name'], 'verbose_name_plural': 'Department'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_name'], 'verbose_name_plural': 'Student'},
        ),
        migrations.AlterModelOptions(
            name='studentid',
            options={'verbose_name_plural': 'Student Id'},
        ),
        migrations.RenameField(
            model_name='department',
            old_name='department',
            new_name='department_name',
        ),
        migrations.AddField(
            model_name='department',
            name='student_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
