# Generated by Django 5.0.1 on 2024-01-13 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_customer_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='studentid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stdt_id', to='Accounts.studentid'),
        ),
        migrations.AlterField(
            model_name='department',
            name='student_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stdt_dept', to='Accounts.department'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stdt_subject', to='Accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject_Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stdt_marks', to='Accounts.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_marks', to='Accounts.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
