# Generated by Django 5.0.1 on 2024-01-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_remove_student_student_id_student_studentid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject_marks',
            options={'verbose_name_plural': 'Marks'},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
    ]
