# Generated by Django 5.0.1 on 2024-01-31 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_subject_marks_options_remove_subject_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('report_card', models.SmallIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stdt_report_card', to='Accounts.student')),
            ],
            options={
                'verbose_name_plural': 'Report Card',
                'unique_together': {('report_card', 'date')},
            },
        ),
    ]
