# Generated by Django 5.0.1 on 2024-01-31 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_alter_report_card_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report_card',
            old_name='report_card',
            new_name='rank',
        ),
        migrations.AlterUniqueTogether(
            name='report_card',
            unique_together={('rank', 'date')},
        ),
    ]
