# Generated by Django 5.0.1 on 2024-02-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_rename_report_card_report_card_rank_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report_card',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='report_card',
            name='total',
            field=models.SmallIntegerField(null=True),
        ),
    ]
