# Generated by Django 5.0 on 2023-12-25 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_about_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Cars',
        ),
    ]
