# Generated by Django 5.0.1 on 2024-01-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0004_recipe_recipe_view_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name_plural': 'Recipe'},
        ),
    ]
